name: Daily Release Monitoring

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  monitor-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get latest FlexProp release
      id: flexprop_release
      run: |
        release_version=$(curl -s https://api.github.com/repos/totalspectrum/spin2cpp/releases/latest | jq -r '.tag_name')
        echo "::set-output name=release_version::$release_version"
    - name: Get latest toolchain release
      id: toolchain_release
      run: |
        release_version=$(curl -s https://api.github.com/repos/RileyMcCarthy/toolchain-flexprop/releases/latest | jq -r '.tag_name')
        echo "::set-output name=release_version::$release_version"
    - name: Release 
      uses: ./.github/workflows/toolchain-flexprop-release.yml
      if: steps.flexprop_release.outputs.release_version != steps.toolchain_release.outputs.release_version
      with:
        branch: ${{ steps.flexprop_release.outputs.release_version }}
        secrets: inherit
