name: toolchain-flexprop
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create release from'     
        required: true
        default: ''
jobs:
  
  build-win-rpi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win32,rpi]
    steps:
      - name: Install MinGW
        if: matrix.os == 'win32'
        run: "sudo apt-get install gcc-mingw-w64-i686"
      - name: Install arm GCC
        if: matrix.os == 'rpi'
        run: "sudo apt install gcc-arm-linux-gnueabihf"
      # Checkout spin2cpp repo and setup environment
      - uses: actions/checkout@v3
        with:
          repository: totalspectrum/spin2cpp
          ref: v${{ github.event.inputs.branch }}
          submodules: recursive
      # make spin2cpp
      - name: Make targets
        run: make CROSS=${{ matrix.os }}
      # Moves files
      - name: Move Files
        run: |
          mkdir ./tools
          cp build-${{ matrix.os }}/flexcc* ./tools/flexcc
          cp build-${{ matrix.os }}/flexspin* ./tools/flexspin
          cp build-${{ matrix.os }}/spin2cpp* ./tools/spin2cpp
      # Uploading build files
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: tools-${{ matrix.os }}
          path: "tools/"
     # Uploading include folder
      - name: Archive include files
        uses: actions/upload-artifact@v3
        with:
          name: include
          path: 'include/'
  
  build-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    steps:
        # Checkout spin2cpp repo and setup environment
      - uses: actions/checkout@v3
        with:
          repository: totalspectrum/spin2cpp
          ref: v${{ github.event.inputs.branch }}
          submodules: recursive
      # make spin2cpp
      - name: Make targets
        run: make
      # Rename tools
      - name: Move Tools
        run: |
          mkdir ./tools
          cp build/flexcc tools/
          cp build/flexspin tools/
          cp build/spin2cpp tools/
      # Uploading build files
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: tools-${{ runner.os }}-${{ runner.arch }}
          path: 'tools/'

  create-release:
    needs: [build-win-rpi, build-linux-macos]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create artifact dir
      run: mkdir -p ./artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - name: Update platformio package.json
      run: >
        echo '
        {
          "name": "toolchain-flexprop",
          "version": "${{ github.event.inputs.branch }}",
          "description": "FlexProp toolchain for parallax devices",
          "keywords": [
            "toolchain",
            "build tools",
            "compiler",
            "assembler",
            "linker",
            "preprocessor",
            "microchip",
            "parallax",
            "propeller"
          ],
          "homepage": "https://github.com/totalspectrum/spin2cpp",
          "license": "GPL-2.0-or-later"
        }
        ' > 'package.json'
    
    # Create build directory
    - name: Create release directory and copy required files
      run: |
        mkdir -p 'bin'
        rm -R -f include
        cp -R artifacts/include ./
        cp artifacts/tools-Linux-X64/flexcc ./bin/flexcc
        cp artifacts/tools-Linux-X64/flexspin ./bin/flexspin
        cp artifacts/tools-Linux-X64/spin2cpp ./bin/spin2cpp
        cp artifacts/tools-macOS-X64/flexcc ./bin/flexcc.mac
        cp artifacts/tools-macOS-X64/flexspin ./bin/flexspin.mac
        cp artifacts/tools-macOS-X64/spin2cpp ./bin/spin2cpp.mac
        cp artifacts/tools-Linux-armv7/flexcc ./bin/flexcc.rpi
        cp artifacts/tools-Linux-armv7/flexspin ./bin/flexspin.rpi
        cp artifacts/tools-Linux-armv7/spin2cpp ./bin/spin2cpp.rpi
        cp artifacts/tools-Windows-X64/flexcc ./bin/flexcc.exe
        cp artifacts/tools-Windows-X64/flexspin ./bin/flexspin.exe
        cp artifacts/tools-Windows-X64/spin2cpp ./bin/spin2cpp.exe
        rm -R artifacts
    
    - name: Change permissions
      run: chmod a+rwx ./bin/*
    
    - name: Push updated package
      run: |
        git config --global user.name 'rileymccarthy'
        git config --global user.email 'riley.mccarthy@yahoo.com'
        git add 'package.json'
        git add './bin/*'
        git add './include/*'
        git commit -am "v${{ github.event.inputs.branch }}"
        git push
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.branch }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
