name: toolchain-flexprop
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create release from'     
        required: true
        default: ''
jobs:
  build-win-x64:
    runs-on: windows-latest
    steps:
      - name: Install Bison
        uses: msys2/setup-msys2@v2
        with:
          install: gcc make bison
        # Checkout spin2cpp repo and setup environment
      - uses: actions/checkout@v3
        with:
          repository: totalspectrum/spin2cpp
          ref: v${{ github.event.inputs.branch }}
          submodules: recursive
      # make spin2cpp
      - name: Make targets (Windows only)
        if: runner.os == 'Windows'
        run: msys2 -c make
      # Rename tools
      - name: Move Tools
        run: |
          mkdir ./tools
          msys2 -c 'cp build/flexcc tools/flexcc.exe'
          msys2 -c 'cp build/flexspin tools/flexspin.exe'
          msys2 -c 'cp build/spin2cpp tools/spin2cpp.exe'
      # Uploading build files
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: tools-${{ runner.os }}-${{ runner.arch }}
          path: 'tools/'
  build-linux-macos-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    steps:
        # Checkout spin2cpp repo and setup environment
      - uses: actions/checkout@v3
        with:
          repository: totalspectrum/spin2cpp
          ref: v${{ github.event.inputs.branch }}
          submodules: recursive
      # make spin2cpp
      - name: Make targets
        run: make
      # Rename tools
      - name: Move Tools
        run: |
          mkdir ./tools
          cp build/flexcc tools/flexcc
          cp build/flexspin tools/flexspin
          cp build/spin2cpp tools/spin2cpp
      # Uploading build files
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: tools-${{ runner.os }}-${{ runner.arch }}
          path: 'tools/'
  build-linux-armv7:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-latest
          - arch: armv7
            distro: ubuntu-latest
    steps:
      # Checkout spin2cpp repo and setup environment
      - uses: actions/checkout@v3
        with:
          repository: totalspectrum/spin2cpp
          ref: v${{ github.event.inputs.branch }}
          submodules: recursive
      # make spin2cpp
      - name: Make targets
        run: make
      # Rename tools
      - name: Move Tools
        run: |
          mkdir ./tools
          cp build/flexcc tools/flexcc${{ runner.arch }}
          cp build/flexspin tools/flexspin${{ runner.arch }}
          cp build/spin2cpp tools/spin2cpp${{ runner.arch }}
      # Uploading build files
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: tools-${{ runner.os }}-${{ runner.arch }}
          path: 'tools/'
       # Uploading include folder
      - name: Archive include files
        uses: actions/upload-artifact@v3
        with:
          name: include
          path: 'include/'
  create-release:
    needs: [build-win-x64, build-linux-macos-x64, build-linux-armv7]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create artifact dir
      run: mkdir -p ./artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - name: Update platformio package.json
      run: >
        echo '
        {
          "name": "toolchain-flexprop",
          "version": "${{ github.event.inputs.branch }}",
          "description": "FlexProp toolchain for parallax devices",
          "keywords": [
            "toolchain",
            "build tools",
            "compiler",
            "assembler",
            "linker",
            "preprocessor",
            "microchip",
            "parallax",
            "propeller"
          ],
          "homepage": "https://github.com/totalspectrum/spin2cpp",
          "license": "GPL-2.0-or-later"
        }
        ' > 'package.json'
    # Create build directory
    - name: Create release directory and copy required files
      run: |
        mkdir -p 'bin'
        rm -R -f include
        cp -R artifacts/tools-Linux/include ./
        cp artifacts/tools-Windows-X64/flexcc.exe ./bin
        cp artifacts/tools-Windows-X64/flexspin.exe ./bin
        cp artifacts/tools-Windows-X64/spin2cpp.exe ./bin
        cp artifacts/tools-Linux-X64/flexcc ./bin
        cp artifacts/tools-Linux-X64/flexspin ./bin
        cp artifacts/tools-Linux-X64/spin2cpp ./bin
        cp artifacts/tools-macOS-X64/flexcc.mac ./bin
        cp artifacts/tools-macOS-X64/flexspin.mac ./bin
        cp artifacts/tools-macOS-X64/spin2cpp.mac ./bin
        rm -R artifacts
    - name: Change permissions
      run: chmod a+rwx ./bin/*
    - name: Push updated package
      run: |
        git config --global user.name 'rileymccarthy'
        git config --global user.email 'riley.mccarthy@yahoo.com'
        git add 'package.json'
        git add './bin/*'
        git add './include/*'
        git commit -am "v${{ github.event.inputs.branch }}"
        git push
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.branch }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
